doc/md/concepts: add info about dev database being emptied after usage
ariga/atlas pull request #1065
Opened 2022-08-18 09:46 UTC by masseelch

2022-08-18 09:48 UTC, hilakashai approved these changes

2022-08-18 09:48 UTC, hilakashai commented on doc/md/concepts/dev.md
> +Atlas cleans up after itself! You can use one instance of a "Dev Database" for multiple environments, as long
```suggestion
Atlas cleans up after itself! You can use the same instance of a "Dev Database" for multiple environments, as long 
```

2022-08-18 09:55 UTC, a8m commented on doc/md/concepts/dev.md
> +:::info
Why here? Put it at the end

2022-08-18 10:12 UTC, a8m requested changes
See my comment, please.

2022-08-19 08:23 UTC, a8m approved these changes

2022-08-19 10:32 UTC, merged