doc/md/guides: Add article about functional indexes in MySQL
ariga/atlas pull request #1389
Opened 2023-01-05 16:12 UTC by priteshtm

2023-01-07 05:41 UTC, a8m commented on doc/md/guides/mysql/functional-indexes.md
> +This is where having knowledge about functional indexes becomes essential. Now, let's try to optimize the query by creating a functional index with the expression “((science + mathematics)/2)” from o
```suggestion
This is where having knowledge about functional indexes becomes essential. Now, let's try to optimize the query by creating a functional index with the expression `((science + mathematics)/2)` from our query, with the following command:
```

2023-01-07 05:46 UTC, a8m commented on doc/md/guides/mysql/functional-indexes.md
> +Migration failures can leave the database in a broken state. Some databases, like MySQL, do not support transactional migrations due to [implicit COMMIT](https://dev.mysql.com/doc/refman/8.0/en/impli
Let’s remove this info block as it’s not 100% correct.

2023-01-07 05:46 UTC, a8m approved these changes

2023-01-08 08:25 UTC, hilakashai requested changes

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +In contrast to a “normal” index which indexes column values, functional key parts can index expression values. Hence, functional key parts enable indexing values which are not stored directly in the
```suggestion
In contrast to a "normal" index which indexes column values, functional key parts can index expression values. Hence, functional key parts enable indexing values which are not stored directly in the table itself. MySQL 8.0.13 and higher have added support for functional key parts.
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +Let’s create a table containing students lists and the marks they received in each subject with the following command:
```suggestion
Let’s create a table containing a list of students and the marks they received in each subject with the following command:
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +We do not have any indexes other than the primary index on the `id` column. Now, suppose we want information about the top ten students who scored best average in math and science combined. Let's que
```suggestion
We do not have any indexes other than the primary index on the `id` column. Now, suppose we want information about the top ten students who scored the best average in math and science combined. Let's query that data with the following command:
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +Oops, that didn’t work! As we mentioned in the [Syntax](link_to_syntax_hashtag) section above, Expressions must be enclosed within parentheses in order to create a functional index. Let’s try this ag
```suggestion
Oops, that didn’t work! As we mentioned in the [syntax](link_to_syntax_hashtag) section above, expressions must be enclosed within parentheses in order to create a functional index. Let’s try this again with the correct syntax:
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +The cost has reduced down to 0.01! Index scan has used the index “functional_idx” in order to execute the query. This is a significant improvement in performance compared to the scenarios above with
```suggestion
The cost has reduced down to 0.01! The index scan has used the index "functional_idx" in order to execute the query. This is a significant improvement in performance compared to the scenarios above with an index on a column (unused) or no index at all (both of which cost 100000+ units).
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +### Limitations:
```suggestion
### Limitations
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +1. Functional indexes can not be defined as primary keys.
```suggestion
1. Functional indexes cannot be defined as primary keys.
```

2023-01-08 08:25 UTC, hilakashai commented on doc/md/guides/mysql/functional-indexes.md
> +We will first use the atlas schema inspect command to get an [HCL](https://atlasgo.io/guides/ddl#hcl) representation of the table we created earlier (without any indexes other than primary index on i
```suggestion
We will first use the `atlas schema inspect` command to get an [HCL](https://atlasgo.io/guides/ddl#hcl) representation of the table we created earlier (without any indexes other than primary index on id column) by using the Atlas CLI:
```

2023-01-09 06:54 UTC, a8m commented on doc/md/guides/mysql/functional-indexes.md
> +Oops, that didn’t work! As we mentioned in the [syntax](https://atlasgo.io/guides/mysql/functional-indexes#syntax) section above, expressions must be enclosed within parentheses in order to create a
```suggestion
Oops, that didn’t work! As we mentioned in the [syntax](#syntax) section above, expressions must be enclosed within parentheses in order to create a functional index. Let’s try this again with the correct syntax:
```

Can you try this instead?

2023-01-10 12:10 UTC, merged