sql/migratespec: support modify_table and add_column
ariga/atlas pull request #246
Opened 2021-11-24 14:43 UTC by rotemtam

Stacked on #245 

Adding first migrate spec types for initial review of the API. 

Starting to add types that capture the different change types from `sql/migrate`.

In HCL, it will look something like:

```hcl
modify_table {
	table = "users"
	add_column {
		column "id" {
			type = "int"
		}
	}
}
```

After building this layer, we can start exploring how the migration document looks like. For example:

```hcl
migration "xyz" {
  up {
     modify_table {
        // ...
     }
  }
  down {
     // ...
  }
}
```

2021-11-24 16:21 UTC, yonidavidson approved these changes
💯 
Just fix linter issues

2021-11-24 20:00 UTC, a8m commented on sql/migratespec/migratespec.go
> +package migratespec
Let's keep this code in `sqlspec`?

2021-11-24 20:04 UTC, a8m requested changes
See my comment.

2021-11-25 08:27 UTC, rotemtam commented on sql/migratespec/migratespec.go
> +package migratespec
done

2021-11-25 08:46 UTC, a8m approved these changes
Please fix the above comments.

2021-11-25 08:46 UTC, a8m commented on sql/sqlspec/migratespec.go
> +		c()
https://github.com/ariga/atlas/blob/master/sql/schema/migrate.go#L24
```suggestion
		change()
```

2021-11-25 08:46 UTC, a8m commented on internal/integration/hclsqlspec/migrate_test.go
> +func Test(t *testing.T) {
```suggestion
func TestMigrate(t *testing.T) {
```

2021-11-25 09:18 UTC, merged