Postgres driver: don't require varchar length
ariga/atlas pull request #539
Opened 2022-01-31 22:06 UTC by edigaryev

Problem: when using Postgres driver, the `character_varying()` does not require a length attribute:

https://github.com/ariga/atlas/blob/ce25dd8f5ae3f594644e6bfb3414b1532bfa3d0b/sql/postgres/sqlspec.go#L338

...yet `varchar()` does:

https://github.com/ariga/atlas/blob/ce25dd8f5ae3f594644e6bfb3414b1532bfa3d0b/sql/postgres/sqlspec.go#L337

The [official PostgreSQL documentation](https://www.postgresql.org/docs/9.3/datatype-character.html) treats these two identically:

>The notations `varchar(n)` and `char(n)` are aliases for character `varying(n)` and `character(n)`, respectively.

2022-02-06 12:49 UTC, rotemtam requested changes
hey @edigaryev !
thanks for working on this, see small comment.

2022-02-06 12:49 UTC, rotemtam commented on sql/postgres/sqlspec_test.go
> +		type = varchar()
```suggestion
		type = varchar
```

this will work but looks nicer as it will be written in the database

2022-02-06 12:49 UTC, rotemtam commented on sql/postgres/sqlspec_test.go
> +		type = character_varying()
```suggestion
		type = character_varying
```
same

2022-02-09 21:58 UTC, rotemtam approved these changes
Thanks for your contribution @edigaryev !

2022-02-09 21:58 UTC, merged

2022-02-09 22:21 UTC, a8m commented
Thanks for the help @edigaryev ❤️