cmd/action: add unit test for env command
ariga/atlas pull request #559
Opened 2022-02-09 21:14 UTC by elad-n

2022-02-09 21:42 UTC, rotemtam requested changes

2022-02-09 21:42 UTC, rotemtam commented on cmd/action/env_test.go
> +
Rm line

2022-02-09 21:42 UTC, rotemtam commented on cmd/action/env_test.go
> +
Rm line

2022-02-14 07:11 UTC, a8m approved these changes

2022-02-14 07:11 UTC, merged