ci: use our crdb image
ariga/atlas pull request #841
Opened 2022-06-01 11:13 UTC by hedwigz

2022-06-02 07:13 UTC, masseelch requested changes
What about the `docker-compose.yml`?

2022-06-06 06:54 UTC, hedwigz commented
> What about the `docker-compose.yml`?

`docker-compose.yml` has the `command` option so that I can start the cockroach image with `start-single-node --insecure` but the GitHub action service doesn't have this option so I built another image to solve that.

2022-06-06 07:01 UTC, a8m commented
Can’t you use run.entrypoint or run.args for this? 
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsentrypoint

2022-06-06 07:02 UTC, a8m commented on .github/workflows/ci.yml
> +        image: hedwigz/cockroachdb-single-node:v21.2.11
I think we can build it in the action and use it here, no?

2022-06-06 10:12 UTC, a8m approved these changes

2022-06-06 10:15 UTC, merged